new changes made
sudh-0/example-git-repo pull request #1
Opened 2021-03-04 10:34 UTC by tany2-apt

Added informations.

2021-03-04 12:16 UTC, sudh-0 requested changes

2021-03-04 12:16 UTC, sudh-0 commented on tanya.md
> +-Working as an intern @aptusdatalabs.com
Remove the `.com`

This is an example of comments in reviews.
You can make further changes to this PR by pushing to the branch in your fork with which the PR was raised @tany2-apt

2021-03-04 14:06 UTC, tany2-apt commented
Added new file Tanya.md, made according to template.md.

2021-03-05 06:43 UTC, sudh-0 approved these changes

2021-03-05 06:44 UTC, merged

2021-03-05 06:45 UTC, sudh-0 commented
@all-contributors please add @tany2-apt for code

2021-03-05 06:50 UTC, sudh-0 commented
@all-contributors please add @tany2-apt for code