Created Anindit.md
sudh-0/example-git-repo pull request #3
Opened 2021-03-04 15:30 UTC by aninditdk

Added details of Anindit Panigrahi

2021-03-05 06:41 UTC, sudh-0 requested changes
Follow the `template.md` and do the changes

2021-03-05 13:13 UTC, aninditdk commented
Good evening sir,

I have created another file with the required changes and made the pull
request.

On Fri, Mar 5, 2021, 12:11 sudh-0 <notifications@github.com> wrote:

> *@sudh-0* requested changes on this pull request.
>
> Follow the template.md and do the changes
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sudh-0/example-git-repo/pull/3#pullrequestreview-604844559>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APPF6HH6R2NVDNXMSLA2RM3TCB4KNANCNFSM4YTOWHZA>
> .
>

2021-03-08 01:39 UTC, sudh-0 approved these changes

2021-03-08 01:39 UTC, merged

2021-03-08 01:39 UTC, sudh-0 commented
@all-contributors please add @aninditdk for code